export const SET_PASSWORD_LENGTH = 'SET_PASSWORD_LENGTH';
export const SET_PASSWORD_AMOUNT = 'SET_PASSWORD_AMOUNT';
export const SET_SMALL_LETTERS = 'SET_SMALL_LETTERS';
export const SET_CAPITAL_LETTERS = 'SET_CAPITAL_LETTERS';
export const SET_SPACES = 'SET_SPACES';
export const SET_NUMBERS = 'SET_NUMBERS';
export const SET_SPECIAL_CHARACTERS = 'SET_SPECIAL_CHARACTERS';
export const SET_BRACKETS = 'SET_BRACKETS';
