export const SET_LANGUAGE_INDEX = 'SET_LANGUAGE_INDEX';
export const SET_THEME_INDEX = 'SET_THEME_INDEX';
export const SET_THEME_TYPE = 'SET_THEME_TYPE';
export const RESET_STATE = 'RESET_STATE';
export const SET_PAGE_INDEX = 'SET_PAGE_INDEX';
